Eatler/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from accounts.api import urls
from main import urls as mainurls
from main.api import urls as main_api_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),
    path('account_api/', include(urls)),
    path('index/',include(mainurls)),
    path('main_api/',include(main_api_urls)),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from django.contrib.auth import logout
from .views import ( RegisterView, DashboardView,
                    LoginView, PhoneVerificationView,
                    IndexView,resend_url,view1,RestaurantView,user_logout)
from django.contrib.auth import views as auth_views
from main.views import homepage
app_name='accounts'
urlpatterns = [
    # url(r'^$', IndexView.as_view(), name='index_page'),
    path('',homepage,name='homepage'),
    path('resend_url/<int:phone_number>/<int:country_code>',resend_url,name='resend_url'),
    url(r'^register/$', RegisterView.as_view(), name="register_url"),
    url(r'^login/$',view1, name="login_url"),
    url(r'^verify/$', PhoneVerificationView, name="phone_verification_url"),
    url(r'^dashboard/$', DashboardView.as_view(), name="dashboard_url"),
    url(r'^login_verify/$',LoginView,name="LoginView"),
    url(r'^logout/$',user_logout,name='logout'),
    url(r'^restaurant/$',RestaurantView,name='restaurant'),
]

main/api/urls.py
from django.urls import path
from main.api import views
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # path('hello/', views.HelloView.as_view(), name='hello'),
    path('query/',views.getQuery.as_view(), name="query"),
    path('product/',views.getProduct.as_view(), name="product_list"),
    # path('login/',views.login.as_view(),name="login"),

    # path('validate/', ValidateOTP.as_view(), name="validate"),
]

# phone number ->otp jayega->otp verify->token return (Login)

# phone_number/full name/country_code/ ->otp bhejega->otp verify -> databases me save karna

main/urls.py
from django.conf.urls import url
from .views import homepage
from django.urls import path
# from .views import ProductFormView,RestaurantFormView
from .views import (RestaurantCreateView,RestaurantListView,RestaurantDetailView,RestaurantUpdateView,
                    RestaurantDeleteView,ProductCreateView,ProductUpdateView,ProductDeleteView)
app_name='main'

urlpatterns = [
    path('',homepage,name='homepage'),
    # path('add_product/',ProductFormView,name="add_product"),
    # path('add_restaurant/',RestaurantFormView,name="add_restaurant"),
    path('list/',RestaurantListView.as_view(),name="list_restaurant"),
    path('create/',RestaurantCreateView.as_view(),name="create_restaurant"),
    path('list/<int:pk>',RestaurantDetailView.as_view(),name="detail_restaurant"),
    path("update/<int:pk>/",RestaurantUpdateView.as_view(),name="update_restaurant"),
    path("delete/<int:pk>/",RestaurantDeleteView.as_view(),name="delete_restaurant"),

    path('<int:pk>/create_product/',ProductCreateView.as_view(),name="create_product"),
    path('update_product/<int:pk>',ProductUpdateView.as_view(),name="update_product"),
    path('delete_product/<int:pk>',ProductDeleteView.as_view(),name="delete_product"),
]

main/models.py
from django.db import models
from accounts.models import User
from django.shortcuts import redirect
from django.urls import reverse
import os
# Create your models here.



class Restaurant(models.Model):

    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    description = models.TextField()
    photo = models.ImageField(upload_to='restaurant_images',blank=True)
    address = models.CharField(max_length=300)
    city = models.CharField(max_length=200)
    email = models.EmailField()
    contact_number = models.IntegerField()

    def __str__(self):
        return self.name

        
    def get_absolute_url(self):
        return reverse("main:list")



class Product(models.Model):
    restaurant=models.ForeignKey(Restaurant,on_delete=models.CASCADE,related_name="products",default=None)
    name = models.CharField(max_length=300)
    description = models.TextField()
    photo = models.ImageField(upload_to='product_images',blank=True)
    add_ons = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6,decimal_places=2)

    def __str__(self):
        return self.name


    # def get_absolute_image(self):
    #     return os.path.join('/product_images', self.photo.name)

main/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext as _
from django.contrib.auth import authenticate
from .models import Product,Restaurant





class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields=['name','description','photo','add_ons','price']



class RestaurantForm(forms.ModelForm):

    class Meta:
        model = Restaurant
        fields=['name','description','photo','address','city','email','contact_number']

main/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from django.conf import settings
from rest_framework import status
from rest_framework.generics import CreateAPIView
from rest_framework.response import Response
from main.models import Restaurant,Product
from django.shortcuts import get_object_or_404
from main.api.serializers import (
    RestaurantSerializer,ProductSerializer
)
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.authtoken.models import Token
import json

from django.http import JsonResponse
from django.forms.models import model_to_dict




class getQuery(CreateAPIView):
    serializer_class = RestaurantSerializer

    def post(self, request, format=None):
        serializer = self.serializer_class(
            data=request.data,
        )
        if serializer.is_valid():
            query = serializer.validated_data['query']
            print(query)
            restaurant_list=Restaurant.objects.raw(query)
            # print(restaurant_list)
            # dict={}
            # for object in restaurant_list:
            #     # dict[object.name] = []  # converts ValuesQuerySet into Python list
            #     # dict[object.name]={'city':object.city,'address':object.address,'photo':object.photo,'description':object.description,'email':object.email,'contact_number':object.contact_number}
            dict1={}
            i=0
            for object in restaurant_list:
                # dict= model_to_dict(object)
                dict1[i]={'name':object.name,'city':object.city,'address':object.address,'description':object.description,'email':object.email,'contact_number':object.contact_number}
                i=i+1
            print(dict1)
            return Response(dict1)




class getProduct(CreateAPIView):
    serializer_class = ProductSerializer

    def post(self, request, format=None):
        serializer = self.serializer_class(
            data=request.data,
        )
        if serializer.is_valid():
            restaurant = serializer.validated_data['restaurant']
            print(restaurant)
            restaurantID=Restaurant.objects.filter(name=restaurant).first()
            print(restaurantID)
            product=Product.objects.filter(restaurant=restaurantID)
            dict1={}
            i=0
            for object in product:
                # dict= model_to_dict(object)
                dict1[i]={'name':object.name,'description':object.description,'add_ons':object.add_ons,'price':object.price}
                i=i+1
            print(dict1)
            return Response(dict1)

main/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic import (View,TemplateView,ListView,DetailView,
                                    CreateView,UpdateView,DeleteView)
from .models import Product,Restaurant
from .forms import ProductForm,RestaurantForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from accounts.decorators import allowed_users

def homepage(request):
    return render(request,'main/index.html')


#
# def ProductFormView(request):
#     if request.method=="POST":
#         product_form = ProductForm(data=request.POST)
#         if product_form.is_valid():
#             product=product_form.save()
#             if 'photo' in request.FILES:
#                 product.photo=request.FILES['photo']
#             product.save()
#         else:    #in case if there is error in validation of input data
#             print(product_form.errors)
#         return redirect("/restaurant")
#     else:      #in case if the method is not post
#         product_form=ProductForm()
#
#     context_dic={"product_form":product_form}
#     return render(request,"main/add_product.html",context_dic)
#
#
# def RestaurantFormView(request):
#     if request.method=="POST":
#         restaurant_form = RestaurantForm(data=request.POST)
#         if restaurant_form.is_valid():
#
#             restaurant=restaurant_form.save(commit=False)
#             restaurant.user = request.user
#             if 'photo' in request.FILES:
#                 restaurant.photo=request.FILES['photo']
#             restaurant.save()
#         else:    #in case if there is error in validation of input data
#             print(restaurant_form.errors)
#         return redirect("/restaurant")
#     else:      #in case if the method is not post
#         restaurant_form=RestaurantForm()
#
#     context_dic={"restaurant_form":restaurant_form}
#     return render(request,"main/add_restaurant.html",context_dic)





@method_decorator(login_required(login_url="/login/"), name='dispatch')
@method_decorator(allowed_users(allowed_roles=['restaurant']),name='dispatch')
class RestaurantListView(ListView):
    context_object_name="restaurants"
    def get_queryset(self):
        return Restaurant.objects.filter(user=self.request.user)

@method_decorator(login_required(login_url="/login/"), name='dispatch')
@method_decorator(allowed_users(allowed_roles=['restaurant']),name='dispatch')
class RestaurantCreateView(CreateView):
    fields=('name','description','photo','address','city','email','contact_number')
    model=Restaurant
    def form_valid(self, form):

        form.instance.user = self.request.user
        if 'photo' in self.request.FILES:
            form.instance.photo=self.request.FILES['photo']
        # print(self.request.user)
        return super(RestaurantCreateView, self).form_valid(form)
    success_url=reverse_lazy("main:list_restaurant")


@method_decorator(login_required(login_url="/login/"), name='dispatch')
@method_decorator(allowed_users(allowed_roles=['restaurant']),name='dispatch')
class RestaurantDetailView(DetailView):
    context_object_name="restaurant_details"
    model = Restaurant


@method_decorator(login_required(login_url="/login/"), name='dispatch')
@method_decorator(allowed_users(allowed_roles=['restaurant']),name='dispatch')
class RestaurantUpdateView(UpdateView):
    fields=("name","description","photo","email","contact_number")
    def get_queryset(self):
        return Restaurant.objects.filter(user=self.request.user)

    def get_success_url(self):
          return reverse_lazy('main:detail_restaurant', kwargs={'pk': self.kwargs['pk']})



@method_decorator(login_required(login_url="/login/"), name='dispatch')
@method_decorator(allowed_users(allowed_roles=['restaurant']),name='dispatch')
class RestaurantDeleteView(DeleteView):
    def get_queryset(self):
        return Restaurant.objects.filter(user=self.request.user)
    success_url=reverse_lazy("main:list_restaurant")




#
# @method_decorator(login_required(login_url="/login/"), name='dispatch')
# @method_decorator(allowed_users(allowed_roles=['restaurant']),name='dispatch')
# class RestaurantListView(ListView):
#     context_object_name="restaurants"
#     def get_queryset(self):
#         return Restaurant.objects.filter(user=self.request.user)

@method_decorator(login_required(login_url="/login/"), name='dispatch')
@method_decorator(allowed_users(allowed_roles=['restaurant']),name='dispatch')
class ProductCreateView(CreateView):
    # fields=('name','description','photo','add_ons','price')
    model=Product
    form_class=ProductForm
    def form_valid(self, form):
        product = form.save(commit=False)
        photo = form.cleaned_data['photo']
        restaurantID=self.kwargs['pk']
        restaurant=Restaurant.objects.get(pk=restaurantID)
        form.instance.restaurant = restaurant
        form.instance.photo=photo
        product.save()
        return super(ProductCreateView, self).form_valid(form)
    def get_success_url(self):
          return reverse_lazy('main:detail_restaurant', kwargs={'pk': self.kwargs['pk']})





@method_decorator(login_required(login_url="/login/"), name='dispatch')
@method_decorator(allowed_users(allowed_roles=['restaurant']),name='dispatch')
class ProductUpdateView(UpdateView):
    fields=('name','description','photo','add_ons','price')
    restaurantID = None
    def get_queryset(self):
        global restaurantID
        productID=self.kwargs['pk']
        product=Product.objects.get(pk=productID)
        restaurant=product.restaurant
        restaurantID=restaurant.pk
        return Product.objects.filter(restaurant=restaurant)


    def get_success_url(self):
          return reverse_lazy('main:detail_restaurant',kwargs={'pk': restaurantID})



@method_decorator(login_required(login_url="/login/"), name='dispatch')
@method_decorator(allowed_users(allowed_roles=['restaurant']),name='dispatch')
class ProductDeleteView(DeleteView):
    restaurantID = None
    def get_queryset(self):
        global restaurantID
        productID=self.kwargs['pk']
        product=Product.objects.get(pk=productID)
        restaurant=product.restaurant
        restaurantID=restaurant.pk
        return Product.objects.filter(restaurant=restaurant)


    def get_success_url(self):
          return reverse_lazy('main:detail_restaurant',kwargs={'pk': restaurantID})

main/templates/main/add_product.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <div class="jumbotron">
    <form class="form-container">
    <form action="{% url "main:add_product"%}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{product_form.as_p}}
      <input type="submit"  value="Add">
    </form>
                </form>
  </div>
  </body>
</html>

main/templates/main/add_restaurant.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <div class="jumbotron">
  <div class="page-wrapper bg-gra-01 p-t-180 p-b-100 font-poppins">
        <div class="wrapper wrapper--w780">
            <div class="card card-3">
                <div class="card-body">
    <form action="{% url "main:add_restaurant"%}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{restaurant_form.as_p}}
      <input type="submit"  value="Add">
    </form>
                </div>
            </div>
        </div>
  </div>
  </div>
  </body>
</html>

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Eatler</title>
      <link href="{% static 'extra/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/restaurant.css' %}" rel="stylesheet">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url "main:homepage"%}">Eatler</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url "main:homepage"%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "main:list_restaurant" %}">Restaurant</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">Delivery Agents</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url "accounts:logout" %}">Logout</a>
          </li>

        </ul>

      </div>
</nav>


{% block body %}
{% endblock %}




  </body>
</html>

main/templates/main/product_confirm_delete.html
{% extends "main/base.html" %}
{% load static %}

{% block body %}
<link rel="stylesheet" type="text/css" href="css/restaurant.css">
<style>
body, html {
  height: 100%;
  margin: 0;
}

    .bg{
    background:url('https://en.freejpg.com.ar/asset/900/42/425e/F100006474.jpg')no-repeat;
     height: 100vh;
     width:  100%;
  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
    }
    .form-container{
    position absolute;
    top:15vh;
    background:#ffc56e !important;
    padding:30px;
    border-radius:10px;
    box-shadow: 0px 0px 10px 0px #000;
    }
    @media only screen and (max-width:1050px){
    .bg{
    background-size:300%;
    }
    }

  </style>
<div class="bg">
   <section class="container-fluid">
    <section class="row justify-content-center">
        <section class="col-md-4 col-md-offset-4">
          <div class="form-container" >

              <p><b>Delete {{product.name}}?</b></p>
              <form method="post" >
                {%csrf_token%}
                <input type="submit" class="btn btn-danger" value="Delete">
                <a href="{%url "main:detail_restaurant" pk=product.restaurant.pk%}">Cancel</a>
              </form>
          </div>
        </section>
    </section>
   </section>


</div>

 {% endblock %}

main/templates/main/product_form.html
{% extends "main/base.html" %}
{% load static %}

{% block body %}
<link rel="stylesheet" type="text/css" href="css/restaurant.css">
<style>
    .bg{
    background:url('https://en.freejpg.com.ar/asset/900/42/425e/F100006474.jpg')no-repeat;
    width:100%
    height:100vh;
    background-size:170%;
    }
    .form-container{
    position absolute;
    top:15vh;
    background:#ffc56e !important;
    padding:30px;
    border-radius:10px;
    box-shadow: 0px 0px 10px 0px #000;
    }
    @media only screen and (max-width:1050px){
    .bg{
    background-size:300%;
    }
    }
  </style>
<div class="jumbotron bg">
   <section class="container-fluid">
    <section class="row justify-content-center">
        <section class="col-12 col-sm-10 col-md-8 col-lg-4">
    <div class="form-container" >
      <h2>
      {%if not form.instance.pk%}
      Add Product
      {%else%}
      Update Product
      {%endif%}
    </h2>
    <form  style="text-align:center; font-weight:bold" method="post" enctype="multipart/form-data">

      {%csrf_token%}
      {{form.as_p}}

      <input type="submit" class="btn btn-primary"  value="submit">
    </form>
    </div>
           </section>
    </section>
</section>
  {% endblock %}
</div>

main/templates/main/restaurant_confirm_delete.html
{% extends "main/base.html" %}
{% load static %}

{% block body %}
<link rel="stylesheet" type="text/css" href="css/restaurant.css">
<style>
    .bg{
    background:url('https://images.unsplash.com/photo-1555396273-367ea4eb4db5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=667&q=80')no-repeat;
    height: 100vh;
     width:  100%;
  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
    }
      .form-container{
    position absolute;
    top:15vh;
    background:#f78e05 !important;
    padding:30px;
    border-radius:10px;
    box-shadow: 0px 0px 10px 0px #000;
    }
    @media only screen and (max-width:1050px){
    .bg{
    background-size:300%;
    }
    }
  </style>

<div class="jumbotron bg">
<section class="container-fluid">
    <section class="row justify-content-center">
        <section class="col-12 col-sm-10 col-md-8 col-lg-4">
            <form class="form-container">

                <p>Delete {{restaurant.name}}?</p>
                <form method="post">
                  {%csrf_token%}
                  <input type="submit" class="btn btn-danger" value="Delete">
                  <a href="{%url "main:list_restaurant"%}">Cancel</a>
                </form>
            </form>
        </section>
    </section>
</section>
</div>
 {% endblock %}

main/templates/main/restaurant_detail.html
{% extends "main/base.html" %}
{% load static %}

{% block body %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<style>
    .container{
    margin-top:8%;
    margin-left:8%;
    }
    .lob:hover{
    -webkit-box-shadow: -1px 9px 40px -12px rgba(0,0,0,0.75);
    -moz-box-shadow: -1px 9px 40px -12px rgba(0,0,0,0.75);
    -box-shadow: -1px 9px 40px -12px rgba(0,0,0,0.75)
}
</style>
<script>
    $(document).ready(function(){
    $('.col-4-lg'):hover{
    function(){
    $(this).animate({
    marginTop:"-=1%",
    },200);
    },
    function(){
    $(this).animate({
    marginTop:"0%"
    },200);
    }
    );
    });
</script>
<link href="{% static 'extra/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<div class="jumbotron">
    <h4 style="font-size: 2.5rem;" class="white">Welcome to {{restaurant_details.name}} Restaurant</h4>

  <div class="row">


    <div class="card mb-3 col-md-6 mx-3" style="max-width: 540px;">
      <div class="row no-gutters">
        <div class="col-4-lg">
          <div class="card-body">
              <p><b>Name : {{restaurant_details.name}}</b></p>
              <p><b>Address :{{restaurant_details.address}}</b></p>
              <p><b>City : {{restaurant_details.city}}</b></p>

            <p> <a class="btn btn-warning" href="{%url "main:update_restaurant" pk=restaurant_details.pk%}">Update Restaurant Details</a> </p>


    <p> <a class="btn btn-danger" href="{%url "main:delete_restaurant" pk=restaurant_details.pk%}">Delete Restaurant</a> </p>

    <p> <a class="btn btn-info" href="{%url "main:create_product" pk=restaurant_details.pk %}">Add Product</a> </p>

          </div>
        </div>
      </div>
    </div>
  </div>
  <h4 style="font-size: 2.5rem;" class="white">List of products in the restaurant :</h4>
    <div class="card-group">
  {%for product in restaurant_details.products.all%}
   <div class="row menu-container">
    <div class="product-top" >
      <div class="col-4-lg ml-3">
       <div class="card lob" style="width:18rem;">
          <div class="card-body">
            <p><b><h4>{{product.name}}</h4>and its price is ${{product.price}}</b></p>

              <div class="image">
                <img src="/media/{{ product.photo}}" class="card-img" alt="Responsive image">
              </div>
              <p><b>{{product.description}}</b></p>
            <p></p>

              <div class="container">
                <p> <a class="btn btn-warning" href="{%url  "main:update_product" pk=product.pk   %}">Update Product</a> </p>
              </div>

              <div class="container">
                <p> <a class="btn btn-danger" href="{%url  "main:delete_product" pk=product.pk   %}">Delete Product</a> </p>
              </div>
           </div>
        </div>
      </div>
    </div>
   </div>
              {%endfor%}
    </div>
</div>
  {% endblock%}

main/templates/main/restaurant_form.html
{% extends "main/base.html" %}
{% load static %}

{% block body %}
<link rel="stylesheet" type="text/css" href="css/restaurant.css">
<style>
    .bg{
    background:url('https://images.unsplash.com/photo-1555396273-367ea4eb4db5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=667&q=80')no-repeat;
    width:100%
    height:100vh;
    background-size:100%;
    }
    .form-container{
    position absolute;
    top:15vh;
    background:#ffc56e !important;
    padding:30px;
    border-radius:10px;
    box-shadow: 0px 0px 10px 0px #000;
    }
    @media only screen and (max-width:1050px){
    .bg{
    background-size:300%;
    }
 }
  </style>
<div class="jumbotron bg">
<section class="container-fluid">
    <section class="row justify-content-center">
        <section class="col-12 col-sm-10 col-md-8 col-lg-4">
    <form class="form-container">
    <h2>
    {%if not form.instance.pk%}
    Add Restaurant
    {%else%}
    Update Restaurant
    {%endif%}
  </h2>
  <form  style="text-align:center;  justify-content:center; align-items:center font-weight:bold" method="post" enctype="multipart/form-data">
      <div class="form-group">
    {%csrf_token%}
    {{form.as_ul}}
    <input type="submit" class="btn btn-primary"  value="submit">
      </div>
  </form>
    </form>
        </section>
    </section>
</section>
{% endblock %}
</div>

main/templates/main/restaurant_list.html
{% extends "main/base.html" %}
{% load static %}

{% block body %}
<link href="{% static 'extra/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

<div class="jumbotron">
  <h2 class="mt-3 mb-4">List Of Restaurants</h2>

  <ol>
    <div class="row card-group">
    {% for restaurant in restaurants%}
      <div class="card mb-3 col-sm-6" style="max-width: 540px;">
      <div class="row no-gutters">
        <div class="col-md-4">
           <p></p>
          <img src="/media/{{restaurant.photo}}" class="card-img" alt="Responsive image">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">{{restaurant.name}}</h5>
            <h5 class="card-title">...</h5>
            <p class="card-text">{{restaurant.description}}</p>

              <a class="btn btn-success" href="{{restaurant.id}}">Visit</a>
          </div>
        </div>
      </div>
      </div>
    {% endfor %}
    </div>
  </ol>
  <a class="btn btn-success"  href="{% url "main:create_restaurant"%}">Add Restaurant</a>
</div>
{% endblock %}